import { Badge } from "@/components/ui/badge";
import { GeneratedExamplesPayload } from "@/lib/types";
import {NoteExampleCard} from "@/components/note/NoteExampleCard";

interface LanguageExamplesProps {
    examples: GeneratedExamplesPayload;
}

export default function LanguageExamples({ examples }: LanguageExamplesProps) {
    return (
        <div className="min-h-screen bg-background">
            {/* Header */}
            <div className="sticky top-0 z-10 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 border-b">
                <div className="container mx-auto px-4 py-4">
                    <div className="flex items-center justify-between">
                        <div>
                            <h1 className="text-2xl font-bold">Darija Learning</h1>
                            <p className="text-sm text-muted-foreground">
                                Topic: {examples.meta.topic} • Level: {examples.meta.level}
                            </p>
                        </div>
                        <Badge variant="outline" className="hidden sm:flex">
                            {examples.meta.model}
                        </Badge>
                    </div>
                </div>
            </div>

            {/* Content */}
            <div className="container mx-auto px-4 py-6">
                <div className="space-y-6 max-w-2xl mx-auto">
                    {examples.examples.map((example, index) => (
                        <NoteExampleCard key={index} example={example} index={index} />
                    ))}
                </div>
            </div>

            {/* Footer */}
            <div className="border-t mt-12">
                <div className="container mx-auto px-4 py-6">
                    <div className="text-center text-sm text-muted-foreground">
                        <p>Generated by {examples.meta.model}</p>
                        <p className="mt-1">
                            {examples.examples.length} examples • {examples.meta.style} style • Max{" "}
                            {examples.meta.maxWords} words
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
